
/*=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
												/* BASE PARA MONITORAMENTO DE TABELAS DO BANCO DE DADOS */
/*=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/

/*
Objetivo: A consulta abaixo tem o objetivo de coletar dados das principais tabelas do banco de dados, para auxiliar no monitoramento dessas tabelas e 
compreender se estão devidamente atualizadas.

Detalhamento: A consulta retorna :
			-- Nome da Tabela, 
			-- Grupo que a tabela pertence, 
			-- Horários que as tabelas dos grupos devem estar atualizadas, 
			-- Data Minima e Maxima das tabelas
			-- Totalidade de Registros de cada tabela
			-- Volumetria de linhas em diferentes periodos (D-1, D-7 e D-15)
			-- Delta comparando o volume de linhas de D-1 com D-7 e D-15
*/

/*=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/




CREATE VIEW DATA_CONTROL.VW_MONITORAMENTO_TABELAS_AGRUPADAS_TEMA AS


--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
--                                                             TABELAS URA
--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/

SELECT 
    'tb_ura_cog_detail' AS NOME_TABELA,
	'Núcleo URA' AS GRUPO_TABELA,
	'MANHÃ AS 09:30' AS PERIODO_VALIDACAO,
	MIN(CAST(initiatedAt AS DATE)) AS DATA_MINIMA,
    MAX(CAST(initiatedAt AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(initiatedAt AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(initiatedAt AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(initiatedAt AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(initiatedAt AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(initiatedAt AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(initiatedAt AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(initiatedAt AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_ura_cog_detail

UNION ALL

SELECT 
    'tb_ura_cog_detail_base_relatorio' AS NOME_TABELA,
	'Núcleo URA' AS GRUPO_TABELA,
	'MANHÃ AS 09:30' AS PERIODO_VALIDACAO,
	MIN(CAST(dth_inicio AS DATE)) AS DATA_MINIMA,
    MAX(CAST(dth_inicio AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(dth_inicio AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(dth_inicio AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(dth_inicio AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(dth_inicio AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(dth_inicio AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(dth_inicio AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(dth_inicio AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_ura_cog_detail_base_relatorio


UNION ALL

--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
--                                                             TABELAS SIEBEL
--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/

SELECT 
    'tb_siebel_attendances' AS NOME_TABELA,
	'Núcleo SIEBEL' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(sr_create_date  AS DATE)) AS DATA_MINIMA,
    MAX(CAST(sr_create_date  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(sr_create_date  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(sr_create_date  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(sr_create_date  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_siebel_attendances

UNION ALL

SELECT
    'tb_rp_siebel_motivo_ctto' AS NOME_TABELA,
	'Núcleo SIEBEL' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(sr_create_date  AS DATE)) AS DATA_MINIMA,
    MAX(CAST(sr_create_date   AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(sr_create_date   AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(sr_create_date   AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(sr_create_date   AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_rp_siebel_motivo_ctto

UNION ALL

SELECT 
	'TB_SIEBEL_REINCIDENCIA_V2' AS NOME_TABELA,
	'Núcleo SIEBEL' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(DATE_TB1 AS DATE)) AS DATA_MINIMA,
    MAX(CAST(DATE_TB1 AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(DATE_TB1  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(DATE_TB1  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(DATE_TB1  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(DATE_TB1 AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DATE_TB1 AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(DATE_TB1 AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DATE_TB1 AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_SIEBEL_REINCIDENCIA_V2


UNION ALL

--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
--                                                             TABELAS CHURN E BASE CLIENTES
--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/


SELECT 
	'TB_SIEBEL_BASE_CLIENTE_GROSS_V2' AS NOME_TABELA,
	'Núcleo CHURN E CLIENTES' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(dt_referencia AS DATE)) AS DATA_MINIMA,
    MAX(CAST(dt_referencia AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(dt_referencia  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(dt_referencia  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(dt_referencia  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(dt_referencia AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(dt_referencia AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(dt_referencia AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(dt_referencia AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_SIEBEL_BASE_CLIENTE_GROSS_V2

UNION ALL

SELECT
	'TB_ATENDIMENTO_ORDEM_DESCONEXAO_CONSOLIDADO' AS NOME_TABELA,
	'Núcleo CHURN E CLIENTES' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(max_data_criacao_sr  AS DATE)) AS DATA_MINIMA,
    MAX(CAST(max_data_criacao_sr  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_ATENDIMENTO_ORDEM_DESCONEXAO_CONSOLIDADO

UNION ALL

SELECT  
	'VW_ATENDIMENTO_ORDEM_DESCONEXAO_CONSOLIDADO' AS NOME_TABELA,
	'Núcleo CHURN E CLIENTES' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(max_data_criacao_sr  AS DATE)) AS DATA_MINIMA,
    MAX(CAST(max_data_criacao_sr  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(max_data_criacao_sr AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM VW_ATENDIMENTO_ORDEM_DESCONEXAO_CONSOLIDADO


UNION ALL

--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
--                                                             TABELAS SCHEDULLE
--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/

SELECT  
	'STG_STAFF_MENSAL_REPROCESSAR' AS NOME_TABELA,
	'Núcleo SCHEDULLE' AS GRUPO_TABELA,
	'TARDE AS 16:00' AS PERIODO_VALIDACAO,
	MIN(CAST(DATA_REFERENCIA  AS DATE)) AS DATA_MINIMA,
    MAX(CAST(DATA_REFERENCIA  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(DATA_REFERENCIA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(DATA_REFERENCIA AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(DATA_REFERENCIA AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(DATA_REFERENCIA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DATA_REFERENCIA AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(DATA_REFERENCIA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DATA_REFERENCIA AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM STG_STAFF_MENSAL_REPROCESSAR

UNION ALL

SELECT 
	'tb_staff_mensal_new' AS NOME_TABELA,
	'Núcleo SCHEDULLE' AS GRUPO_TABELA,
	'TARDE AS 16:00' AS PERIODO_VALIDACAO,
	MIN(CAST(data_referencia  AS DATE)) AS DATA_MINIMA,
    MAX(CAST(data_referencia  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(data_referencia AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(data_referencia AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(data_referencia AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(data_referencia AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(data_referencia AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(data_referencia AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(data_referencia AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_staff_mensal_new


UNION ALL

--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
--                                                  TABELAS CHAMADAS (NOC, ECH E CALLBACK)
--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/

SELECT 
	'TB_BASE_CONSOLIDADA_NOC' AS NOME_TABELA,
	'Núcleo CHAMADAS' AS GRUPO_TABELA,
	'MANHÃ AS 09:30' AS PERIODO_VALIDACAO,
	MIN(CAST(data  AS DATE)) AS DATA_MINIMA,
    MAX(CAST(data  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(data AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(data AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(data AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(data AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(data AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(data AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(data AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_BASE_CONSOLIDADA_NOC

UNION ALL

SELECT 
	'TB_ECH_HVDN' AS NOME_TABELA,
	'Núcleo CHAMADAS' AS GRUPO_TABELA,
	'MANHÃ AS 09:30' AS PERIODO_VALIDACAO,
	MIN(CAST(row_date  AS DATE)) AS DATA_MINIMA,
    MAX(CAST(row_date  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(row_date AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(row_date AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(row_date AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(row_date AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(row_date AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(row_date AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(row_date AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM BDS.[Data_reports].[TB_ECH_HVDN]

UNION ALL

SELECT 
	'TB_ECH_RESULTS_CONSOLIDADO' AS NOME_TABELA,
	'Núcleo CHAMADAS' AS GRUPO_TABELA,
	'MANHÃ AS 09:30' AS PERIODO_VALIDACAO,
	MIN(CAST(DATA AS DATE)) AS DATA_MINIMA,
    MAX(CAST(DATA AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_ECH_RESULTS_CONSOLIDADO

UNION ALL

SELECT 
	'TB_ECH_DETALHADO' AS NOME_TABELA,
	'Núcleo CHAMADAS' AS GRUPO_TABELA,
	'MANHÃ AS 09:30' AS PERIODO_VALIDACAO,
	MIN(CAST(segstart AS DATE)) AS DATA_MINIMA,
    MAX(CAST(segstart  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM BDS.[Data_reports].[TB_ECH_DETALHADO]

UNION ALL

SELECT 
	'tb_ech_detalhado_ENRIQUECIDO_URA' AS NOME_TABELA,
	'Núcleo CHAMADAS' AS GRUPO_TABELA,
	'MANHÃ AS 09:30' AS PERIODO_VALIDACAO,
	MIN(CAST(segstart AS DATE)) AS DATA_MINIMA,
    MAX(CAST(segstart  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(segstart AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_ech_detalhado_ENRIQUECIDO_URA

UNION ALL

SELECT 
	'TB_ECH_TMT' AS NOME_TABELA,
	'Núcleo CHAMADAS' AS GRUPO_TABELA,
	'MANHÃ AS 09:30' AS PERIODO_VALIDACAO,
	MIN(CAST(ROW_DATE AS DATE)) AS DATA_MINIMA,
    MAX(CAST(ROW_DATE AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(ROW_DATE AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(ROW_DATE AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(ROW_DATE AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(ROW_DATE AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(ROW_DATE AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(ROW_DATE AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(ROW_DATE AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_ECH_TMT

UNION ALL

SELECT 
	'TB_BASE_CALLBACK_AUTOMATICO' AS NOME_TABELA,
	'Núcleo CHAMADAS' AS GRUPO_TABELA,
	'MANHÃ AS 09:30' AS PERIODO_VALIDACAO,
	MIN(CAST(Data AS DATE)) AS DATA_MINIMA,
    MAX(CAST(Data AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(Data AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(Data AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(Data AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(Data AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(Data AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(Data AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(Data AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_BASE_CALLBACK_AUTOMATICO

UNION ALL

SELECT
	'tb_ech_callback' AS NOME_TABELA,
	'Núcleo CHAMADAS' AS GRUPO_TABELA,
	'MANHÃ AS 09:30' AS PERIODO_VALIDACAO,
	MIN(CAST(DTH_FOTO AS DATE)) AS DATA_MINIMA,
    MAX(CAST(DTH_FOTO AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(DTH_FOTO AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(DTH_FOTO AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(DTH_FOTO AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(DTH_FOTO AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DTH_FOTO AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(DTH_FOTO AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DTH_FOTO AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_ech_callback

UNION ALL

--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
--                                                  TABELAS CANAIS DE TEXTO
--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/

SELECT 
	'TB_BASE_UNICA_CHAT' AS NOME_TABELA,
	'Núcleo CANAIS DE TEXTO' AS GRUPO_TABELA,
	'MANHÃ AS 11:00' AS PERIODO_VALIDACAO,
	MIN(CAST(DT_INICIO_AVI AS DATE)) AS DATA_MINIMA,
    MAX(CAST(DT_INICIO_AVI AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_BASE_UNICA_CHAT

UNION ALL

SELECT 
	'TB_RP_CHAT' AS NOME_TABELA,
	'Núcleo CANAIS DE TEXTO' AS GRUPO_TABELA,
	'MANHÃ AS 11:00' AS PERIODO_VALIDACAO,
	MIN(CAST(DT_INICIO_AVI AS DATE)) AS DATA_MINIMA,
    MAX(CAST(DT_INICIO_AVI AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_RP_CHAT

UNION ALL

SELECT
	'TB_BASE_PRODUTIVIDADE_CHAT' AS NOME_TABELA,
	'Núcleo CANAIS DE TEXTO' AS GRUPO_TABELA,
	'MANHÃ AS 11:00' AS PERIODO_VALIDACAO,
	MIN(CAST(inicio_fila AS DATE)) AS DATA_MINIMA,
    MAX(CAST(inicio_fila AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(inicio_fila AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(inicio_fila AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(inicio_fila AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(inicio_fila AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(inicio_fila AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(inicio_fila AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(inicio_fila AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_BASE_PRODUTIVIDADE_CHAT

UNION ALL

SELECT
	'TB_chat_transbordo' AS NOME_TABELA,
	'Núcleo CANAIS DE TEXTO' AS GRUPO_TABELA,
	'MANHÃ AS 11:00' AS PERIODO_VALIDACAO,
	MIN(CAST(DT_INICIO_AVI AS DATE)) AS DATA_MINIMA,
    MAX(CAST(DT_INICIO_AVI AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DT_INICIO_AVI AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_chat_transbordo


UNION ALL


--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
--                                                  TABELAS CONTRATO
--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/


SELECT
	'TB_CONTRATO_SHORT_CALL' AS NOME_TABELA,
	'Núcleo CONTRATO' AS GRUPO_TABELA,
	'MANHÃ AS 09:00' AS PERIODO_VALIDACAO,
	MIN(CAST(SEGSTART AS DATE)) AS DATA_MINIMA,
    MAX(CAST(SEGSTART AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_CONTRATO_SHORT_CALL


UNION ALL

SELECT 
	'TB_CONTRATO_ECH_RECHAMADA' AS NOME_TABELA,
	'Núcleo CONTRATO' AS GRUPO_TABELA,
	'MANHÃ AS 09:00' AS PERIODO_VALIDACAO,
	MIN(CAST(HORARIO_INICIO_ATD AS DATE)) AS DATA_MINIMA,
    MAX(CAST(HORARIO_INICIO_ATD  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(HORARIO_INICIO_ATD  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(HORARIO_INICIO_ATD  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(HORARIO_INICIO_ATD  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(HORARIO_INICIO_ATD AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(HORARIO_INICIO_ATD AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(HORARIO_INICIO_ATD AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(HORARIO_INICIO_ATD AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_CONTRATO_ECH_RECHAMADA

UNION ALL

SELECT
	'TB_CONTRATO_ECH_RECHAMADA_TRANSF' AS NOME_TABELA,
	'Núcleo CONTRATO' AS GRUPO_TABELA,
	'MANHÃ AS 09:00' AS PERIODO_VALIDACAO,
	MIN(CAST(HORARIO_INICIO_ATD  AS DATE)) AS DATA_MINIMA,
    MAX(CAST(HORARIO_INICIO_ATD  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(HORARIO_INICIO_ATD  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(HORARIO_INICIO_ATD  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(HORARIO_INICIO_ATD  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(HORARIO_INICIO_ATD AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(HORARIO_INICIO_ATD AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(HORARIO_INICIO_ATD AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(HORARIO_INICIO_ATD AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_CONTRATO_ECH_RECHAMADA_TRANSF

UNION ALL

SELECT
	'TB_CONTRATO_CONTATO_INICIAL_BD' AS NOME_TABELA,
	'Núcleo CONTRATO' AS GRUPO_TABELA,
	'MANHÃ AS 09:00' AS PERIODO_VALIDACAO,
	MIN(CAST(SEGSTART AS DATE)) AS DATA_MINIMA,
    MAX(CAST(SEGSTART AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_CONTRATO_CONTATO_INICIAL_BD

UNION ALL

SELECT 
	'TB_CONTRATO_CONTATO_INICIAL_BD_TRANSF' AS NOME_TABELA,
	'Núcleo CONTRATO' AS GRUPO_TABELA,
	'MANHÃ AS 09:00' AS PERIODO_VALIDACAO,
	MIN(CAST(SEGSTART AS DATE)) AS DATA_MINIMA,
    MAX(CAST(SEGSTART AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(SEGSTART AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_CONTRATO_CONTATO_INICIAL_BD_TRANSF

UNION ALL

SELECT 
	'TB_CONTRATO_CHURN_V2' AS NOME_TABELA,
	'Núcleo CONTRATO' AS GRUPO_TABELA,
	'MANHÃ AS 09:00' AS PERIODO_VALIDACAO,
	MIN(CAST(DATA AS DATE)) AS DATA_MINIMA,
    MAX(CAST(DATA AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DATA AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_CONTRATO_CHURN_V2 


UNION ALL

--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
--                                                  TABELAS OUVIDORIA
--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/

SELECT 
    'TB_SIEBEL_OUVIDORIA_BKP' AS NOME_TABELA,
    'Núcleo OUVIDORIA' AS GRUPO_TABELA,
	'MANHÃ AS 11:45' AS PERIODO_VALIDACAO,
    MIN(CAST(sr_create_date AS DATE)) AS DATA_MINIMA,
    MAX(CAST(sr_create_date AS DATE)) AS DATA_MAXIMA,
    COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(sr_create_date AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_SIEBEL_OUVIDORIA_BKP

UNION ALL

SELECT
	'tb_siebel_ouvidoria_turbina' AS NOME_TABELA,
	'Núcleo OUVIDORIA' AS GRUPO_TABELA,
	'MANHÃ AS 11:45' AS PERIODO_VALIDACAO,
	MIN(CAST(DATA_ENTRADA_TURBINA AS DATE)) AS DATA_MINIMA,
    MAX(CAST(DATA_ENTRADA_TURBINA AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(DATA_ENTRADA_TURBINA  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(DATA_ENTRADA_TURBINA  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(DATA_ENTRADA_TURBINA  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(DATA_ENTRADA_TURBINA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DATA_ENTRADA_TURBINA AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(DATA_ENTRADA_TURBINA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DATA_ENTRADA_TURBINA AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_siebel_ouvidoria_turbina

UNION ALL

SELECT 
	'TB_PESQUISA_BKO_ANALITICO' AS NOME_TABELA,
	'Núcleo OUVIDORIA' AS GRUPO_TABELA,
	'MANHÃ AS 11:45' AS PERIODO_VALIDACAO,
	MIN(CAST([Dt. Envio Tracking] AS DATE)) AS DATA_MINIMA,
    MAX(CAST([Dt. Envio Tracking]  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST([Dt. Envio Tracking]  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST([Dt. Envio Tracking]  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST([Dt. Envio Tracking]  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST([Dt. Envio Tracking] AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST([Dt. Envio Tracking] AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST([Dt. Envio Tracking] AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST([Dt. Envio Tracking] AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM TB_PESQUISA_BKO_ANALITICO

UNION ALL

SELECT  
	'tb_bo_triagem' AS NOME_TABELA,
	'Núcleo OUVIDORIA' AS GRUPO_TABELA,
	'MANHÃ AS 11:45' AS PERIODO_VALIDACAO,
	MIN(CAST(DATA_TERMINO AS DATE)) AS DATA_MINIMA,
    MAX(CAST(DATA_TERMINO  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(DATA_TERMINO  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(DATA_TERMINO  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(DATA_TERMINO  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(DATA_TERMINO AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DATA_TERMINO AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(DATA_TERMINO AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DATA_TERMINO AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_bo_triagem


UNION ALL

--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/
--                                                  TABELAS ODC
--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-*/

SELECT
	'tb_consumidor_gov' AS NOME_TABELA,
	'Núcleo ODC' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST([data abertura] AS DATE)) AS DATA_MINIMA,
    MAX(CAST([data abertura]  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST([data abertura]  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST([data abertura]  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST([data abertura]  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST([data abertura] AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST([data abertura] AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST([data abertura] AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST([data abertura] AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_consumidor_gov

UNION ALL

SELECT
	'tb_turbina_gov_visao_supervisor' AS NOME_TABELA,
	'Núcleo ODC' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST([data abertura] AS DATE)) AS DATA_MINIMA,
    MAX(CAST([data abertura]  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST([data abertura]  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST([data abertura]  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST([data abertura]  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST([data abertura] AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST([data abertura] AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST([data abertura] AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST([data abertura] AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_turbina_gov_visao_supervisor

UNION ALL

SELECT
	'tb_odc_gov' AS NOME_TABELA,
	'Núcleo ODC' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(data_turbina AS DATE)) AS DATA_MINIMA,
    MAX(CAST(data_turbina  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(data_turbina  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(data_turbina  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(data_turbina  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(data_turbina AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(data_turbina AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(data_turbina AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(data_turbina AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_odc_gov

UNION ALL

SELECT
	'tb_juridico_benner' AS NOME_TABELA,
	'Núcleo ODC' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(inicio_tarefa AS DATE)) AS DATA_MINIMA,
    MAX(CAST(inicio_tarefa  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(inicio_tarefa  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(inicio_tarefa AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(inicio_tarefa AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(inicio_tarefa AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(inicio_tarefa AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(inicio_tarefa AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(inicio_tarefa AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_juridico_benner

UNION ALL

SELECT 
	'tb_odc_jec_entrantes_Fechados' AS NOME_TABELA,
	'Núcleo ODC' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(Inicio_Tarefa AS DATE)) AS DATA_MINIMA,
    MAX(CAST(Inicio_Tarefa  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(Inicio_Tarefa  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(Inicio_Tarefa  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(Inicio_Tarefa  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(inicio_tarefa AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(inicio_tarefa AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(inicio_tarefa AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(inicio_tarefa AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_odc_jec_entrantes_Fechados


UNION ALL

SELECT
	'tb_anatel_consumidor' AS NOME_TABELA,
	'Núcleo ODC' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(DataRegistro AS DATE)) AS DATA_MINIMA,
    MAX(CAST(DataRegistro  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(DataRegistro  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(DataRegistro  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(DataRegistro  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(DataRegistro AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DataRegistro AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(DataRegistro AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(DataRegistro AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_anatel_consumidor

UNION ALL

SELECT
	'tb_odc_anatel' AS NOME_TABELA,
	'Núcleo ODC' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(dt_ABERTURA AS DATE)) AS DATA_MINIMA,
    MAX(CAST(dt_ABERTURA  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(dt_ABERTURA  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(dt_ABERTURA  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(dt_ABERTURA  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(dt_ABERTURA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(dt_ABERTURA AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(dt_ABERTURA AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(dt_ABERTURA AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_odc_anatel


UNION ALL

SELECT
	'tb_procon' AS NOME_TABELA,
	'Núcleo ODC' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(datadasolicitacao AS DATE)) AS DATA_MINIMA,
    MAX(CAST(datadasolicitacao  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(datadasolicitacao  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(datadasolicitacao  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(datadasolicitacao  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(datadasolicitacao AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(datadasolicitacao AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(datadasolicitacao AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(datadasolicitacao AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_procon

UNION ALL

SELECT
	'tb_proconsumidor' AS NOME_TABELA,
	'Núcleo ODC' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(dt_abertura  AS DATE)) AS DATA_MINIMA,
    MAX(CAST(dt_abertura  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(dt_abertura  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(dt_abertura  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(dt_abertura  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(dt_abertura AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(dt_abertura AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(dt_abertura AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(dt_abertura AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_proconsumidor

UNION ALL

SELECT
	'tb_odc_gov' AS NOME_TABELA,
	'Núcleo ODC' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(data_geracao  AS DATE)) AS DATA_MINIMA,
    MAX(CAST(data_geracao  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(data_geracao AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(data_geracao AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(data_geracao AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(data_geracao AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(data_geracao AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(data_geracao AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(data_geracao AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
	GETDATE() AS Data_Consulta
FROM tb_turbina_consumidor_procon_supervisor

UNION ALL

SELECT
	'tb_odc_proconbrasil' AS NOME_TABELA,
	'Núcleo ODC' AS GRUPO_TABELA,
	'MANHÃ AS 10:00' AS PERIODO_VALIDACAO,
	MIN(CAST(data_geracao  AS DATE)) AS DATA_MINIMA,
    MAX(CAST(data_geracao  AS DATE)) AS DATA_MAXIMA,
	COUNT(*) AS TOTAL_REGISTROS,
    SUM(CASE WHEN CAST(data_geracao  AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_1,
    SUM(CASE WHEN CAST(data_geracao  AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_7,
    SUM(CASE WHEN CAST(data_geracao  AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS VOLUME_LINHAS_D_15,
	(SUM(CASE WHEN CAST(data_geracao AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(data_geracao AS DATE) = CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D7,
	(SUM(CASE WHEN CAST(data_geracao AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN 1 ELSE 0 END)) - SUM(CASE WHEN CAST(data_geracao AS DATE) = CAST(DATEADD(DAY, -15, GETDATE()) AS DATE) THEN 1 ELSE 0 END) AS DELTA_D1_D15,
    GETDATE() AS Data_Consulta
FROM tb_odc_proconbrasil